#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2154

function package_unypkg {
    cd /uny/pkg || exit
    for pkg in /uny/sources/release-*; do
        vdet_new_file="${pkg//release-/vdet-}"
        vdet_content="$(cat "$vdet_new_file")"

        pkg="$(echo "$pkg" | grep -Eo "release.*" | sed -e "s|release-||")"
        pkgv="$(echo "$vdet_content" | head -n 1)"

        cp "$vdet_new_file" "$pkg"/"$pkgv"/vdet

        source_archive_orig="$(echo /uny/sources/"$pkg"-"$pkgv".tar.*)"
        source_archive_new="$(echo "$source_archive_orig" | sed -r -e "s|^.*/||" -e "s|(\.tar.*$)|-source\1|")"
        cp -a "$source_archive_orig" "$source_archive_new"
        cp -a /uny/uny/build/logs/"$pkg"-*.log "$pkg"-build.log
        XZ_OPT="-9 --threads=0" tar -cJpf unypkg-"$pkg".tar.xz "$pkg"

        gh -R unypkg/"$pkg" release create "$pkgv"-"$uny_build_date_now" --generate-notes \
            "$pkg/$pkgv/vdet#vdet - $vdet_content" unypkg-"$pkg".tar.xz "$pkg"-build.log "$source_archive_new"
    done
}
