#!/usr/bin/env sh
# shellcheck disable=2034,2154

update_unypkg() {
    # Download or update the unypkg script
    # shellcheck disable=SC2154
    echo "Updating the unypkg script."
    cd "$unypkg_install_dir" || exit
    wget -q https://github.com/unypkg/unypkg/archive/refs/heads/release.tar.gz -O- | tar xz
    update_success="$?"
    cp -a unypkg-release/* .
    rm -rf unypkg-release
    chmod +x "$unypkg_install_dir"/bin/unyp "$unypkg_install_dir"/bin/unyc
    ln -sf "$unypkg_install_dir"/bin/unyp /bin/unyp
    ln -sf "$unypkg_install_dir"/bin/unyc /bin/unyc
    if [ "$update_success" = 0 ]; then
        echo "Successfully updated unypkg."
    else
        echo "Something went wrong, unypkg did not update right."
    fi
}

get_pkg_release_version_and_download_url() {
    tags_page=$(wget -q -O- "https://github.com/unypkg/${pkg}/tags")
    git_tags="$(echo "$tags_page" | grep -o '/unypkg/'"$pkg"'/releases/tag/[^"]*' | sed "s|/unypkg/$pkg/releases/tag/||" | sort -ur)"
    while ! echo "$tags_page" | grep -q "There aren’t any releases here"; do
        after_tag="$(echo "$git_tags" | tail -n1)"
        tags_page=$(wget -q -O- "https://github.com/unypkg/${pkg}/tags?after=${after_tag}")
        if echo "$tags_page" | grep -qo '/unypkg/'"$pkg"'/releases/tag/[^"]*'; then
            git_tags="$git_tags $(
                echo
                echo "$tags_page" | grep -o '/unypkg/'"$pkg"'/releases/tag/[^"]*' | sed "s|/unypkg/$pkg/releases/tag/||" | sort -ur
            )"
        fi
    done

    pkg_release="$(echo "$git_tags" | sort | grep "^$pkgveropt" | tail -n1)"
    [ -z "$pkg_release" ] && echo "There is no release for the package $pkg with that version. Aborting." && return #exit
    pkgver="$(echo "$pkg_release" | sed "s|-.*$||")"
    download_url="https://github.com/unypkg/$pkg/releases/download/$pkg_release"
}

download_and_install() {
    echo "${print_indent}Downloading and installing: $pkg $pkg_release"
    [ -n "$pkgdet1" ] && pkgsdir="/$pkgdet1"
    [ -n "$pkgdet2" ] && pkgnode="/$pkgdet2"
    [ -n "$pkgdet3" ] && pkgnode="/$pkgdet2/$pkgdet3"
    wget -q "$download_url/unypkg-$pkg.tar.xz" -O- | tar xJ -C /uny/pkg "$pkg"/"$pkgver""$pkgsdir""$pkgnode" "$pkg"/"$pkgver"/.uny 2>/dev/null
}
